//
// Copyright 2022 Pendo inc.
// This file has been automatically generated by Pendo' namespacing script.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Namespaced Header

#ifndef __PENDO_NAMESPACE_PREFIX_
#error You must define __PENDO_NAMESPACE_PREFIX_ in your project settings in order to use a Pendo namespace.
#else

// MACROS
#ifndef __PENDO_NS_SYMBOL
// We need to have multiple levels of macros here so that __PENDO_NAMESPACE_PREFIX_ is
// properly replaced by the time we concatenate the namespace prefix.
#define __PENDO_NS_REWRITE(namespace,symbol) namespace ## _ ## symbol
#define __PENDO_NS_BRIDGE_(namespace,symbol) __PENDO_NS_REWRITE(namespace,symbol)
#define __PENDO_NS_SYMBOL(symbol           ) __PENDO_NS_BRIDGE_(__PENDO_NAMESPACE_PREFIX_,symbol)
#endif
// MACROS END
    
// Classes
#ifndef ASAbsoluteLayoutSpec
#define ASAbsoluteLayoutSpec __PENDO_NS_SYMBOL(ASAbsoluteLayoutSpec)
#endif
#ifndef ASAbstractLayoutController
#define ASAbstractLayoutController __PENDO_NS_SYMBOL(ASAbstractLayoutController)
#endif
#ifndef ASAbstractRunLoopQueue
#define ASAbstractRunLoopQueue __PENDO_NS_SYMBOL(ASAbstractRunLoopQueue)
#endif
#ifndef ASAccessibilityCustomAction
#define ASAccessibilityCustomAction __PENDO_NS_SYMBOL(ASAccessibilityCustomAction)
#endif
#ifndef ASAccessibilityElement
#define ASAccessibilityElement __PENDO_NS_SYMBOL(ASAccessibilityElement)
#endif
#ifndef ASAsciiArtBoxCreator
#define ASAsciiArtBoxCreator __PENDO_NS_SYMBOL(ASAsciiArtBoxCreator)
#endif
#ifndef ASAsyncTransactionOperation
#define ASAsyncTransactionOperation __PENDO_NS_SYMBOL(ASAsyncTransactionOperation)
#endif
#ifndef ASBackgroundLayoutSpec
#define ASBackgroundLayoutSpec __PENDO_NS_SYMBOL(ASBackgroundLayoutSpec)
#endif
#ifndef ASBasicImageDownloader
#define ASBasicImageDownloader __PENDO_NS_SYMBOL(ASBasicImageDownloader)
#endif
#ifndef ASBasicImageDownloaderContext
#define ASBasicImageDownloaderContext __PENDO_NS_SYMBOL(ASBasicImageDownloaderContext)
#endif
#ifndef ASBatchContext
#define ASBatchContext __PENDO_NS_SYMBOL(ASBatchContext)
#endif
#ifndef ASButtonNode
#define ASButtonNode __PENDO_NS_SYMBOL(ASButtonNode)
#endif
#ifndef ASCATransactionQueue
#define ASCATransactionQueue __PENDO_NS_SYMBOL(ASCATransactionQueue)
#endif
#ifndef ASCellNode
#define ASCellNode __PENDO_NS_SYMBOL(ASCellNode)
#endif
#ifndef ASCenterLayoutSpec
#define ASCenterLayoutSpec __PENDO_NS_SYMBOL(ASCenterLayoutSpec)
#endif
#ifndef ASCollectionElement
#define ASCollectionElement __PENDO_NS_SYMBOL(ASCollectionElement)
#endif
#ifndef ASCollectionFlowLayoutDelegate
#define ASCollectionFlowLayoutDelegate __PENDO_NS_SYMBOL(ASCollectionFlowLayoutDelegate)
#endif
#ifndef ASCollectionGalleryLayoutDelegate
#define ASCollectionGalleryLayoutDelegate __PENDO_NS_SYMBOL(ASCollectionGalleryLayoutDelegate)
#endif
#ifndef ASCollectionLayout
#define ASCollectionLayout __PENDO_NS_SYMBOL(ASCollectionLayout)
#endif
#ifndef ASCollectionLayoutCache
#define ASCollectionLayoutCache __PENDO_NS_SYMBOL(ASCollectionLayoutCache)
#endif
#ifndef ASCollectionLayoutContext
#define ASCollectionLayoutContext __PENDO_NS_SYMBOL(ASCollectionLayoutContext)
#endif
#ifndef ASCollectionLayoutState
#define ASCollectionLayoutState __PENDO_NS_SYMBOL(ASCollectionLayoutState)
#endif
#ifndef ASCollectionNode
#define ASCollectionNode __PENDO_NS_SYMBOL(ASCollectionNode)
#endif
#ifndef ASCollectionView
#define ASCollectionView __PENDO_NS_SYMBOL(ASCollectionView)
#endif
#ifndef ASCollectionViewFlowLayoutInspector
#define ASCollectionViewFlowLayoutInspector __PENDO_NS_SYMBOL(ASCollectionViewFlowLayoutInspector)
#endif
#ifndef ASCollectionViewLayoutController
#define ASCollectionViewLayoutController __PENDO_NS_SYMBOL(ASCollectionViewLayoutController)
#endif
#ifndef ASCollectionViewLayoutInspector
#define ASCollectionViewLayoutInspector __PENDO_NS_SYMBOL(ASCollectionViewLayoutInspector)
#endif
#ifndef ASCollectionViewProxy
#define ASCollectionViewProxy __PENDO_NS_SYMBOL(ASCollectionViewProxy)
#endif
#ifndef ASConfiguration
#define ASConfiguration __PENDO_NS_SYMBOL(ASConfiguration)
#endif
#ifndef ASConfigurationManager
#define ASConfigurationManager __PENDO_NS_SYMBOL(ASConfigurationManager)
#endif
#ifndef ASControlNode
#define ASControlNode __PENDO_NS_SYMBOL(ASControlNode)
#endif
#ifndef ASControlTargetAction
#define ASControlTargetAction __PENDO_NS_SYMBOL(ASControlTargetAction)
#endif
#ifndef ASCornerLayoutSpec
#define ASCornerLayoutSpec __PENDO_NS_SYMBOL(ASCornerLayoutSpec)
#endif
#ifndef ASDKNavigationController
#define ASDKNavigationController __PENDO_NS_SYMBOL(ASDKNavigationController)
#endif
#ifndef ASDKViewController
#define ASDKViewController __PENDO_NS_SYMBOL(ASDKViewController)
#endif
#ifndef ASDataController
#define ASDataController __PENDO_NS_SYMBOL(ASDataController)
#endif
#ifndef ASDefaultPlayButton
#define ASDefaultPlayButton __PENDO_NS_SYMBOL(ASDefaultPlayButton)
#endif
#ifndef ASDefaultPlaybackButton
#define ASDefaultPlaybackButton __PENDO_NS_SYMBOL(ASDefaultPlaybackButton)
#endif
#ifndef ASDelegateProxy
#define ASDelegateProxy __PENDO_NS_SYMBOL(ASDelegateProxy)
#endif
#ifndef ASDisplayNode
#define ASDisplayNode __PENDO_NS_SYMBOL(ASDisplayNode)
#endif
#ifndef ASDisplayNodeCornerLayerDelegate
#define ASDisplayNodeCornerLayerDelegate __PENDO_NS_SYMBOL(ASDisplayNodeCornerLayerDelegate)
#endif
#ifndef ASDisplayNodeTipState
#define ASDisplayNodeTipState __PENDO_NS_SYMBOL(ASDisplayNodeTipState)
#endif
#ifndef ASEditableTextNode
#define ASEditableTextNode __PENDO_NS_SYMBOL(ASEditableTextNode)
#endif
#ifndef ASElementMap
#define ASElementMap __PENDO_NS_SYMBOL(ASElementMap)
#endif
#ifndef ASHighlightOverlayLayer
#define ASHighlightOverlayLayer __PENDO_NS_SYMBOL(ASHighlightOverlayLayer)
#endif
#ifndef ASImageNode
#define ASImageNode __PENDO_NS_SYMBOL(ASImageNode)
#endif
#ifndef ASImageNodeContentsKey
#define ASImageNodeContentsKey __PENDO_NS_SYMBOL(ASImageNodeContentsKey)
#endif
#ifndef ASImageNodeDrawParameters
#define ASImageNodeDrawParameters __PENDO_NS_SYMBOL(ASImageNodeDrawParameters)
#endif
#ifndef ASInsetLayoutSpec
#define ASInsetLayoutSpec __PENDO_NS_SYMBOL(ASInsetLayoutSpec)
#endif
#ifndef ASIntegerMap
#define ASIntegerMap __PENDO_NS_SYMBOL(ASIntegerMap)
#endif
#ifndef ASLayout
#define ASLayout __PENDO_NS_SYMBOL(ASLayout)
#endif
#ifndef ASLayoutElementContext
#define ASLayoutElementContext __PENDO_NS_SYMBOL(ASLayoutElementContext)
#endif
#ifndef ASLayoutElementStyle
#define ASLayoutElementStyle __PENDO_NS_SYMBOL(ASLayoutElementStyle)
#endif
#ifndef ASLayoutManager
#define ASLayoutManager __PENDO_NS_SYMBOL(ASLayoutManager)
#endif
#ifndef ASLayoutSpec
#define ASLayoutSpec __PENDO_NS_SYMBOL(ASLayoutSpec)
#endif
#ifndef ASLayoutTransition
#define ASLayoutTransition __PENDO_NS_SYMBOL(ASLayoutTransition)
#endif
#ifndef ASMainSerialQueue
#define ASMainSerialQueue __PENDO_NS_SYMBOL(ASMainSerialQueue)
#endif
#ifndef ASMultiplexImageNode
#define ASMultiplexImageNode __PENDO_NS_SYMBOL(ASMultiplexImageNode)
#endif
#ifndef ASMutableAttributedStringBuilder
#define ASMutableAttributedStringBuilder __PENDO_NS_SYMBOL(ASMutableAttributedStringBuilder)
#endif
#ifndef ASMutableElementMap
#define ASMutableElementMap __PENDO_NS_SYMBOL(ASMutableElementMap)
#endif
#ifndef ASNetworkImageLoadInfo
#define ASNetworkImageLoadInfo __PENDO_NS_SYMBOL(ASNetworkImageLoadInfo)
#endif
#ifndef ASNetworkImageNode
#define ASNetworkImageNode __PENDO_NS_SYMBOL(ASNetworkImageNode)
#endif
#ifndef ASNodeAncestryEnumerator
#define ASNodeAncestryEnumerator __PENDO_NS_SYMBOL(ASNodeAncestryEnumerator)
#endif
#ifndef ASNodeController
#define ASNodeController __PENDO_NS_SYMBOL(ASNodeController)
#endif
#ifndef ASNullLayoutSpec
#define ASNullLayoutSpec __PENDO_NS_SYMBOL(ASNullLayoutSpec)
#endif
#ifndef ASOverlayLayoutSpec
#define ASOverlayLayoutSpec __PENDO_NS_SYMBOL(ASOverlayLayoutSpec)
#endif
#ifndef ASPagerFlowLayout
#define ASPagerFlowLayout __PENDO_NS_SYMBOL(ASPagerFlowLayout)
#endif
#ifndef ASPagerNode
#define ASPagerNode __PENDO_NS_SYMBOL(ASPagerNode)
#endif
#ifndef ASPagerNodeProxy
#define ASPagerNodeProxy __PENDO_NS_SYMBOL(ASPagerNodeProxy)
#endif
#ifndef ASPanningOverriddenUITextView
#define ASPanningOverriddenUITextView __PENDO_NS_SYMBOL(ASPanningOverriddenUITextView)
#endif
#ifndef ASPendingStateController
#define ASPendingStateController __PENDO_NS_SYMBOL(ASPendingStateController)
#endif
#ifndef ASRangeController
#define ASRangeController __PENDO_NS_SYMBOL(ASRangeController)
#endif
#ifndef ASRatioLayoutSpec
#define ASRatioLayoutSpec __PENDO_NS_SYMBOL(ASRatioLayoutSpec)
#endif
#ifndef ASRelativeLayoutSpec
#define ASRelativeLayoutSpec __PENDO_NS_SYMBOL(ASRelativeLayoutSpec)
#endif
#ifndef ASResponderChainEnumerator
#define ASResponderChainEnumerator __PENDO_NS_SYMBOL(ASResponderChainEnumerator)
#endif
#ifndef ASRunLoopQueue
#define ASRunLoopQueue __PENDO_NS_SYMBOL(ASRunLoopQueue)
#endif
#ifndef ASScrollNode
#define ASScrollNode __PENDO_NS_SYMBOL(ASScrollNode)
#endif
#ifndef ASScrollView
#define ASScrollView __PENDO_NS_SYMBOL(ASScrollView)
#endif
#ifndef ASSection
#define ASSection __PENDO_NS_SYMBOL(ASSection)
#endif
#ifndef ASStackLayoutSpec
#define ASStackLayoutSpec __PENDO_NS_SYMBOL(ASStackLayoutSpec)
#endif
#ifndef ASTabBarController
#define ASTabBarController __PENDO_NS_SYMBOL(ASTabBarController)
#endif
#ifndef ASTableLayoutController
#define ASTableLayoutController __PENDO_NS_SYMBOL(ASTableLayoutController)
#endif
#ifndef ASTableNode
#define ASTableNode __PENDO_NS_SYMBOL(ASTableNode)
#endif
#ifndef ASTableView
#define ASTableView __PENDO_NS_SYMBOL(ASTableView)
#endif
#ifndef ASTableViewProxy
#define ASTableViewProxy __PENDO_NS_SYMBOL(ASTableViewProxy)
#endif
#ifndef ASTextAttachment
#define ASTextAttachment __PENDO_NS_SYMBOL(ASTextAttachment)
#endif
#ifndef ASTextBackedString
#define ASTextBackedString __PENDO_NS_SYMBOL(ASTextBackedString)
#endif
#ifndef ASTextBinding
#define ASTextBinding __PENDO_NS_SYMBOL(ASTextBinding)
#endif
#ifndef ASTextBorder
#define ASTextBorder __PENDO_NS_SYMBOL(ASTextBorder)
#endif
#ifndef ASTextCacheValue
#define ASTextCacheValue __PENDO_NS_SYMBOL(ASTextCacheValue)
#endif
#ifndef ASTextCellNode
#define ASTextCellNode __PENDO_NS_SYMBOL(ASTextCellNode)
#endif
#ifndef ASTextContainer
#define ASTextContainer __PENDO_NS_SYMBOL(ASTextContainer)
#endif
#ifndef ASTextDebugOption
#define ASTextDebugOption __PENDO_NS_SYMBOL(ASTextDebugOption)
#endif
#ifndef ASTextDecoration
#define ASTextDecoration __PENDO_NS_SYMBOL(ASTextDecoration)
#endif
#ifndef ASTextHighlight
#define ASTextHighlight __PENDO_NS_SYMBOL(ASTextHighlight)
#endif
#ifndef ASTextKitComponents
#define ASTextKitComponents __PENDO_NS_SYMBOL(ASTextKitComponents)
#endif
#ifndef ASTextKitComponentsTextView
#define ASTextKitComponentsTextView __PENDO_NS_SYMBOL(ASTextKitComponentsTextView)
#endif
#ifndef ASTextKitContext
#define ASTextKitContext __PENDO_NS_SYMBOL(ASTextKitContext)
#endif
#ifndef ASTextKitEntityAttribute
#define ASTextKitEntityAttribute __PENDO_NS_SYMBOL(ASTextKitEntityAttribute)
#endif
#ifndef ASTextKitFontSizeAdjuster
#define ASTextKitFontSizeAdjuster __PENDO_NS_SYMBOL(ASTextKitFontSizeAdjuster)
#endif
#ifndef ASTextKitRenderer
#define ASTextKitRenderer __PENDO_NS_SYMBOL(ASTextKitRenderer)
#endif
#ifndef ASTextKitShadower
#define ASTextKitShadower __PENDO_NS_SYMBOL(ASTextKitShadower)
#endif
#ifndef ASTextKitTailTruncater
#define ASTextKitTailTruncater __PENDO_NS_SYMBOL(ASTextKitTailTruncater)
#endif
#ifndef ASTextKitTextCheckingResult
#define ASTextKitTextCheckingResult __PENDO_NS_SYMBOL(ASTextKitTextCheckingResult)
#endif
#ifndef ASTextLayout
#define ASTextLayout __PENDO_NS_SYMBOL(ASTextLayout)
#endif
#ifndef ASTextLine
#define ASTextLine __PENDO_NS_SYMBOL(ASTextLine)
#endif
#ifndef ASTextLinePositionSimpleModifier
#define ASTextLinePositionSimpleModifier __PENDO_NS_SYMBOL(ASTextLinePositionSimpleModifier)
#endif
#ifndef ASTextNode
#define ASTextNode __PENDO_NS_SYMBOL(ASTextNode)
#endif
#ifndef ASTextNode2
#define ASTextNode2 __PENDO_NS_SYMBOL(ASTextNode2)
#endif
#ifndef ASTextNodeDrawParameter
#define ASTextNodeDrawParameter __PENDO_NS_SYMBOL(ASTextNodeDrawParameter)
#endif
#ifndef ASTextNodeRendererKey
#define ASTextNodeRendererKey __PENDO_NS_SYMBOL(ASTextNodeRendererKey)
#endif
#ifndef ASTextNodeWordKerner
#define ASTextNodeWordKerner __PENDO_NS_SYMBOL(ASTextNodeWordKerner)
#endif
#ifndef ASTextPosition
#define ASTextPosition __PENDO_NS_SYMBOL(ASTextPosition)
#endif
#ifndef ASTextRange
#define ASTextRange __PENDO_NS_SYMBOL(ASTextRange)
#endif
#ifndef ASTextRunDelegate
#define ASTextRunDelegate __PENDO_NS_SYMBOL(ASTextRunDelegate)
#endif
#ifndef ASTextRunGlyphRange
#define ASTextRunGlyphRange __PENDO_NS_SYMBOL(ASTextRunGlyphRange)
#endif
#ifndef ASTextSelectionRect
#define ASTextSelectionRect __PENDO_NS_SYMBOL(ASTextSelectionRect)
#endif
#ifndef ASTextShadow
#define ASTextShadow __PENDO_NS_SYMBOL(ASTextShadow)
#endif
#ifndef ASTraitCollection
#define ASTraitCollection __PENDO_NS_SYMBOL(ASTraitCollection)
#endif
#ifndef ASWeakMap
#define ASWeakMap __PENDO_NS_SYMBOL(ASWeakMap)
#endif
#ifndef ASWeakMapEntry
#define ASWeakMapEntry __PENDO_NS_SYMBOL(ASWeakMapEntry)
#endif
#ifndef ASWeakProxy
#define ASWeakProxy __PENDO_NS_SYMBOL(ASWeakProxy)
#endif
#ifndef ASWeakSet
#define ASWeakSet __PENDO_NS_SYMBOL(ASWeakSet)
#endif
#ifndef ASWrapperCellNode
#define ASWrapperCellNode __PENDO_NS_SYMBOL(ASWrapperCellNode)
#endif
#ifndef ASWrapperLayoutSpec
#define ASWrapperLayoutSpec __PENDO_NS_SYMBOL(ASWrapperLayoutSpec)
#endif
//#ifndef CABasicAnimation
//#define CABasicAnimation __PENDO_NS_SYMBOL(CABasicAnimation)
//#endif
//#ifndef CADisplayLink
//#define CADisplayLink __PENDO_NS_SYMBOL(CADisplayLink)
//#endif
//#ifndef CAEAGLLayer
//#define CAEAGLLayer __PENDO_NS_SYMBOL(CAEAGLLayer)
//#endif
//#ifndef CALayer
//#define CALayer __PENDO_NS_SYMBOL(CALayer)
//#endif
//#ifndef CAMediaTimingFunction
//#define CAMediaTimingFunction __PENDO_NS_SYMBOL(CAMediaTimingFunction)
//#endif
//#ifndef CATransaction
//#define CATransaction __PENDO_NS_SYMBOL(CATransaction)
//#endif
#ifndef PodsDummy_Texture
#define PodsDummy_Texture __PENDO_NS_SYMBOL(PodsDummy_Texture)
#endif
#ifndef _ASAnimatedTransitionContext
#define _ASAnimatedTransitionContext __PENDO_NS_SYMBOL(_ASAnimatedTransitionContext)
#endif
#ifndef _ASAsyncTransaction
#define _ASAsyncTransaction __PENDO_NS_SYMBOL(_ASAsyncTransaction)
#endif
#ifndef _ASAsyncTransactionGroup
#define _ASAsyncTransactionGroup __PENDO_NS_SYMBOL(_ASAsyncTransactionGroup)
#endif
#ifndef _ASCollectionGalleryLayoutInfo
#define _ASCollectionGalleryLayoutInfo __PENDO_NS_SYMBOL(_ASCollectionGalleryLayoutInfo)
#endif
#ifndef _ASCollectionPendingState
#define _ASCollectionPendingState __PENDO_NS_SYMBOL(_ASCollectionPendingState)
#endif
#ifndef _ASCollectionReusableView
#define _ASCollectionReusableView __PENDO_NS_SYMBOL(_ASCollectionReusableView)
#endif
#ifndef _ASCollectionViewCell
#define _ASCollectionViewCell __PENDO_NS_SYMBOL(_ASCollectionViewCell)
#endif
#ifndef _ASDisplayLayer
#define _ASDisplayLayer __PENDO_NS_SYMBOL(_ASDisplayLayer)
#endif
#ifndef _ASDisplayView
#define _ASDisplayView __PENDO_NS_SYMBOL(_ASDisplayView)
#endif
#ifndef _ASGalleryLayoutItem
#define _ASGalleryLayoutItem __PENDO_NS_SYMBOL(_ASGalleryLayoutItem)
#endif
#ifndef _ASHierarchyChangeSet
#define _ASHierarchyChangeSet __PENDO_NS_SYMBOL(_ASHierarchyChangeSet)
#endif
#ifndef _ASHierarchyItemChange
#define _ASHierarchyItemChange __PENDO_NS_SYMBOL(_ASHierarchyItemChange)
#endif
#ifndef _ASHierarchySectionChange
#define _ASHierarchySectionChange __PENDO_NS_SYMBOL(_ASHierarchySectionChange)
#endif
#ifndef _ASPendingState
#define _ASPendingState __PENDO_NS_SYMBOL(_ASPendingState)
#endif
#ifndef _ASRangeDebugBarView
#define _ASRangeDebugBarView __PENDO_NS_SYMBOL(_ASRangeDebugBarView)
#endif
#ifndef _ASRangeDebugOverlayView
#define _ASRangeDebugOverlayView __PENDO_NS_SYMBOL(_ASRangeDebugOverlayView)
#endif
#ifndef _ASTablePendingState
#define _ASTablePendingState __PENDO_NS_SYMBOL(_ASTablePendingState)
#endif
#ifndef _ASTableViewCell
#define _ASTableViewCell __PENDO_NS_SYMBOL(_ASTableViewCell)
#endif
#ifndef _ASTextInputTraitsPendingState
#define _ASTextInputTraitsPendingState __PENDO_NS_SYMBOL(_ASTextInputTraitsPendingState)
#endif
#ifndef _ASTransitionContext
#define _ASTransitionContext __PENDO_NS_SYMBOL(_ASTransitionContext)
#endif
// Classes END

// Functions
// Functions END

// Externs
// Externs END

#endif
